#!/usr/bin/env bash
set -euo pipefail

# Custom git merge driver for _index.md files
# -------------------------------------------
#
# Splits the file at the *** separator. Everything above *** (frontmatter
# and link block) is regenerated by wiki update, so we take
# "ours" unconditionally. Everything below *** is manually written
# content, so we do a normal three-way merge that may produce conflicts.
#
# Install via .gitattributes:
#   **/_index.md merge=wiki-index
#
# Configure in .git/config or .gitconfig:
#   [merge "wiki-index"]
#     name = wiki index merge (auto-resolve generated sections)
#     driver = bash <path>/merge_index.sh %A %O %B

OURS="$1"
BASE="$2"
THEIRS="$3"

split_at_separator() {
    local FILE="$1"
    local ABOVE="$2"
    local BELOW="$3"
    # skip a leading YAML frontmatter block (--- ... ---) before searching, so a
    # bare *** inside a multi-line block scalar (e.g. a desc) is not mistaken for
    # the links/content separator and split inside the frontmatter
    local SCAN_FROM=1
    if [[ "$(head -1 "$FILE")" =~ ^[[:space:]]*---[[:space:]]*$ ]]; then
        local FM_END
        FM_END=$(tail -n +2 "$FILE" | grep -n '^---[[:space:]]*$' \
            | head -1 | cut -d: -f1 || true)
        [[ -n "$FM_END" ]] && SCAN_FROM=$((FM_END + 2))
    fi
    # find the first *** line at/after the frontmatter (separator between links
    # and content); user content below may contain additional *** thematic breaks
    local SEP_LINE
    SEP_LINE=$(tail -n +"$SCAN_FROM" "$FILE" | grep -n '^\*\*\*[[:space:]]*$' \
        | head -1 | cut -d: -f1 || true)
    if [[ -z "$SEP_LINE" ]]; then
        # no separator -- treat the whole file as content (below) so it gets a
        # full three-way merge rather than silently taking ours and dropping theirs
        : >"$ABOVE"
        cp "$FILE" "$BELOW"
    else
        # SEP_LINE is relative to SCAN_FROM -- convert to an absolute line number
        local ABS_SEP=$((SCAN_FROM + SEP_LINE - 1))
        head -n "$ABS_SEP" "$FILE" >"$ABOVE"
        tail -n +"$((ABS_SEP + 1))" "$FILE" >"$BELOW"
    fi
}

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

split_at_separator "$OURS" "$TMPDIR/ours_above" "$TMPDIR/ours_below"
split_at_separator "$BASE" "$TMPDIR/base_above" "$TMPDIR/base_below"
split_at_separator "$THEIRS" "$TMPDIR/theirs_above" "$TMPDIR/theirs_below"

# above ***: take ours (regenerated by wiki update)
cp "$TMPDIR/ours_above" "$TMPDIR/result_above"

# below ***: three-way merge (may produce conflict markers)
MERGE_EXIT=0
git merge-file -p -L ours -L base -L theirs \
    "$TMPDIR/ours_below" "$TMPDIR/base_below" "$TMPDIR/theirs_below" \
    >"$TMPDIR/result_below" || MERGE_EXIT=$?

# recombine
cat "$TMPDIR/result_above" "$TMPDIR/result_below" >"$OURS"

exit "$MERGE_EXIT"
