name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
      - name: Cache pre-commit hooks
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install package with lint dependencies
        run: ./install.sh --groups=lint
      - name: Run pre-commit
        run: uvx pre-commit run --all-files --show-diff-on-failure --color=always
      - name: Check that project is up-to-date with template
        run: uv run --no-sync cruft check
      - name: Reject forbidden file patterns
        run: test -z "$(find . -name "*.rej" -print -quit)" || exit 1
