name: tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
      - name: Install package with test dependencies
        run: ./install.sh --all-extras --groups=test
      - name: Run tests
        run: uv run --no-sync pytest --cov --cov-report=xml
      - name: Report coverage
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v6.0.2
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
